### ISSUE TITLE
HomeAssistant errors on climate discovery

### ISSUE THREAD

**Issue by neillt** [excaliburpartners/HAILogger#13]
I just got OmniLink-Bridge 1.1.4 up and running... it's talking to my OmniProII just great!  I am using it as the shim between my Omni and HomeAssistant via MQTT.

However, while HA does discover everything about the panel, the single thermostat I have is not being parsed correctly.  This is a Carrier Infinity heat pump system that is using the supported HAI interface into the Omni via serial port.

Unfortunately this means the thermostat is not being imported.

The logs in HA state:

`Exception in async_discover when dispatching 'mqtt_discovery_new_climate_mqtt': ({'current_temperature_topic': 'omnilink/thermostat1/current_temperature', 'temperature_low_state_topic': 'omnilink/thermostat1/temperature_heat_state', 'temperature_low_command_topic': 'omnilink/thermostat1/temperature_heat_command', 'temperature_high_state_topic': 'omnilink/thermostat1/temperature_cool_state', 'temperature_high_command_topic': 'omnilink/thermostat1/temperature_cool_command', 'min_temp': '45', 'max_temp': '95', 'mode_state_topic': 'omnilink/thermostat1/mode_state', 'mode_command_topic': 'omnilink/thermostat1/mode_command', 'modes': ['auto', 'off', 'cool', 'heat'], 'fan_mode_state_topic': 'omnilink/thermostat1/fan_mode_state', 'fan_mode_command_topic': 'omnilink/thermostat1/fan_mode_command', 'fan_modes': ['auto', 'on', 'cycle'], 'hold_state_topic': 'omnilink/thermostat1/hold_state', 'hold_command_topic': 'omnilink/thermostat1/hold_command', 'name': 'Heat Pump', 'state_topic': None, 'availability_topic': 'omnilink/status', 'platform': 'mqtt'},)
Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/mqtt/climate.py", line 246, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)

  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)

  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)

  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)

voluptuous.error.MultipleInvalid: extra keys not allowed @ data['state_topic']`

**Comment by neillt** [comment]
Welp, nevermind... some simple googling revealed that I needed to put:

climate:
  - platform: mqtt

In my HA configuration.yaml.  All seems good now.
